- name: Check OS distribution and version
  hosts: all
  user: root
  tasks:
    - name: Detect systemd service manager (Ubuntu 15.04+)
      set_fact:
        ansible_service_mgr: "systemd"
        when: >
          ansible_distribution|lower == 'ubuntu' and
          ansible_distribution_version|version_compare('15.04', '>=')

    - name: Detect upstart service manager (Ubuntu 14.04 - 14.10)
      set_fact:
        ansible_service_mgr: "upstart"
        when: >
          ansible_distribution|lower == 'ubuntu' and
          (ansible_distribution_version|version_compare('14.04', '>=') and
          ansible_distribution_version|version_compare('15.04', '<'))
