---
- name: Install the designate components
  hosts: designate_all
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - include: ../../openstack-ansible/playbooks/common-tasks/os-lxc-container-setup.yml
    - include: ../../openstack-ansible/playbooks/common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-designate"
            dest: "/var/log/designate"
    - include: ../../openstack-ansible/playbooks/common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ designate_rabbitmq_userid }}"
        password: "{{ designate_rabbitmq_password }}"
        vhost: "{{ designate_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ designate_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['designate_all'][0]
        - groups[designate_rabbitmq_host_group] | length > 0
    - include: ../../openstack-ansible/playbooks/common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ designate_rabbitmq_telemetry_userid }}"
        password: "{{ designate_rabbitmq_telemetry_password }}"
        vhost: "{{ designate_rabbitmq_telemetry_vhost }}"
        _rabbitmq_host_group: "{{ designate_rabbitmq_telemetry_host_group }}"
      when:
        - designate_ceilometer_enabled | bool
        - inventory_hostname == groups['designate_all'][0]
        - groups[designate_rabbitmq_telemetry_host_group] is defined
        - groups[designate_rabbitmq_telemetry_host_group] | length > 0
        - groups[designate_rabbitmq_telemetry_host_group] != groups[designate_rabbitmq_host_group]
    - include: ../../openstack-ansible/playbooks/common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ designate_galera_user }}"
        password: "{{ designate_galera_password }}"
        login_host: "{{ designate_galera_address }}"
        db_name: "{{ designate_galera_database_name }}"
      when: inventory_hostname == groups['designate_all'][0]
    - include: ../../openstack-ansible/playbooks/common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ designate_pool_manager_galera_user }}"
        password: "{{ designate_pool_manager_galera_password }}"
        login_host: "{{ designate_pool_manager_galera_address }}"
        db_name: "{{ designate_pool_manager_galera_database_name }}"
      when: inventory_hostname == groups['designate_all'][0]


  roles:
    - role: "os_designate"
      designate_venv_tag: "{{ openstack_release }}"
      designate_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/designate-{{ openstack_release }}-{{ ansible_architecture | lower }}.tgz"
      tags:
        - "os-designate"
    - { role: "openstack_openrc", tags: [ "openstack-openrc" ] }
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: designate_log_rotate
      rsyslog_client_log_dir: "/var/log/designate"
      rsyslog_client_config_name: "99-designate-rsyslog-client.conf"
      tags:
        - "designate-rsyslog-client"
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
