---
- name: Install trove server
  hosts: trove_all
  gather_facts: "{{ gather_facts | default(True) }}"
  user: root
  pre_tasks:
    - include: ../../openstack-ansible/playbooks/common-tasks/os-lxc-container-setup.yml
    - include: ../../openstack-ansible/playbooks/common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ trove_rabbitmq_userid }}"
        password: "{{ trove_rabbitmq_password }}"
        vhost: "{{ trove_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ trove_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['trove_all'][0]
        - groups[trove_rabbitmq_host_group] | length > 0
    - include: ../../openstack-ansible/playbooks/common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ trove_rabbitmq_telemetry_userid }}"
        password: "{{ trove_rabbitmq_telemetry_password }}"
        vhost: "{{ trove_rabbitmq_telemetry_vhost }}"
        _rabbitmq_host_group: "{{ trove_rabbitmq_telemetry_host_group }}"
      when:
        - trove_ceilometer_enabled | bool
        - inventory_hostname == groups['trove_all'][0]
        - groups[trove_rabbitmq_telemetry_host_group] is defined
        - groups[trove_rabbitmq_telemetry_host_group] | length > 0
        - groups[trove_rabbitmq_telemetry_host_group] != groups[trove_rabbitmq_host_group]
    - include: ../../openstack-ansible/playbooks/common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-trove"
            dest: "/var/log/trove"
    - include: ../../openstack-ansible/playbooks/common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ trove_galera_user }}"
        password: "{{ trove_galera_password }}"
        login_host: "{{ trove_galera_address }}"
        db_name: "{{ trove_galera_database_name }}"
      when: inventory_hostname == groups['trove_all'][0]
    - include: ../../openstack-ansible/playbooks/common-tasks/package-cache-proxy.yml
  roles:
    - role: "os_trove"
      trove_venv_tag: "{{ openstack_release }}"
      trove_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/trove-{{ openstack_release }}-{{ ansible_architecture | lower }}.tgz"
    - role: "openstack_openrc"
      tags:
        - openrc
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: trove_log_rotate
      rsyslog_client_log_dir: "/var/log/trove"
      rsyslog_client_config_name: "99-trove-rsyslog-client.conf"
      tags:
        - rsyslog
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
    pip_lock_to_internal_repo: "{{ (pip_links | length) >= 1 }}"
    trove_service_publicuri_proto: "{{ openstack_service_publicuri_proto }}"
    trove_cinder_url: "{{ trove_service_publicuri_proto }}://{{ external_lb_vip_address }}:{{ cinder_service_port|default('8776') }}/v1"
    trove_swift_url: "{{ trove_service_publicuri_proto }}://{{ external_lb_vip_address }}:{{ swift_proxy_port|default('8080') }}/v1/AUTH_"
  tags:
    - trove
